### ISSUE TITLE
Folders will not mount under Virtualbox 5

### ISSUE THREAD

**Issue by steveswinsburg** [hilverd/vagrant-ubuntu-oracle-xe#26]
I am using Virtualbox 5 and the following error is given:
````
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,dmode=777,fmode=666 home_vagrant_vagrant-ubuntu-oracle-xe /home/vagrant/vagrant-ubuntu-oracle-xe
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant`,dmode=777,fmode=666 home_vagrant_vagrant-ubuntu-oracle-xe /home/vagrant/vagrant-ubuntu-oracle-xe

The error output from the last command was:

stdin: is not a tty
````

Virtualbox guest additions is installed but it is 4.3.12.

To fix this, the version of GA needs to be updated.

Maybe it could be an optional install and we can place the ISO into a directory for bootstrapping?

**Comment by bbozo** [comment]
Any workaround for this? I haven't been able to mount the GA to update it :-/

**Comment by hilverd** [comment]
For some reason I had left `config.vbguest.auto_update = false` in the `Vagrantfile` :neutral_face:. I have now changed it to `true`, so [vbguest](https://github.com/dotless-de/vagrant-vbguest) will hopefully be able to update your Guest Additions.

**Comment by bbozo** [comment]
Aaaa wow, thank you very much :D many thanks :)
